# Generated by Django 6.0.1 on 2026-01-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_id', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
    ]
