# Generated by Django 5.2.12 on 2026-04-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psaors',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='psauths',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='psendpoints',
            options={'managed': False},
        ),
    ]
