# Generated by Django 5.2.12 on 2026-05-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_psaors_options_alter_psauths_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=12, unique=True)),
                ('telephone_model', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phone_config',
                'managed': True,
            },
        ),
    ]
