# Generated by Django 5.2.15 on 2026-07-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_phoneconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneConfig',
        ),
    ]
